import type { NextPage } from "next";
import Head from "next/head";
import { useSession, signIn, signOut } from "next-auth/react";
import { FormEvent, useState } from "react";
import FormItem from "@/components/FormItem";

const Home: NextPage = () => {
	const { data: session, status } = useSession();
	const [when_from, setWhen_from] = useState("");
	const [when_to, setWhen_to] = useState("");
	const [where, setWhere] = useState("");
	const [guests, setGuests] = useState("");

	const handleSubmit = (event: FormEvent<HTMLFormElement>) => {
		event.preventDefault();
		console.log(
			`Looking for listings in ${where} from ${when_from} to ${when_to} for ${guests} people`
		);
	};

	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="absolute min-h-screen top-0 left-0 w-full">
				<form
					className="flex flex-col items-center justify-center min-h-[inherit]"
					onSubmit={handleSubmit}
				>
					<FormItem name="where" value={where} valueSetter={setWhere} />
					<FormItem
						name="from"
						value={when_from}
						valueSetter={setWhen_from}
						type="date"
					/>
					<FormItem
						name="to"
						value={when_to}
						valueSetter={setWhen_to}
						type="date"
					/>
					<FormItem
						name="guests"
						value={guests}
						valueSetter={setGuests}
						type="number"
					/>
					<button type="submit">Find</button>
				</form>
			</div>
			<div className="flex gap-4 justify-end px-8 py-4 relative">
				{status === "authenticated" ? (
					<>
						Signed in as {session.user?.name} <br />
						<button onClick={() => signOut()}>Sign out</button>
					</>
				) : (
					<>
						Not signed in <br />
						<button onClick={() => signIn()}>Sign in</button>
					</>
				)}
			</div>
		</>
	);
};

export default Home;
