import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { useSession, signIn, signOut } from "next-auth/react";

const Home: NextPage = () => {
	const hello = trpc.useQuery(["example.hello", { text: " tRPC" }]);
	// const all = trpc.useQuery(["auth.getSession"]);
	const { data: session } = useSession();

	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="w-screen min-h-screen flex flex-col justify-center items-center p-4 overflow-y-scroll">
				<div className="pt-6 text-2xl flex justify-center items-center w-full">
					{hello.data ? <p>{hello.data.greeting}</p> : <p>Loading..</p>}
				</div>
			</div>
			{/* {all.data?.user ? <p>{all.data.user.name}</p> : <p>Loading..</p>} */}
			{session ? (
				<>
					Signed in as {session.user?.name} <br />
					<button onClick={() => signOut()}>Sign out</button>
				</>
			) : (
				<>
					Not signed in <br />
					<button onClick={() => signIn()}>Sign in</button>
				</>
			)}
		</>
	);
};

export default Home;
